### ISSUE TITLE
deferCount is not increasing

### ISSUE THREAD

**Issue by djhvscf** [rebus-org/Rebus.AmazonSQS#33]
Hi,

When we try to setup the second level retry configuration, the deferCount header increases only to 1, after that it is not increasing more.

Sometimes when it reaches the deferCount = 1, it is duplicating the messages.

Rebus.AmazonSqs: 6.2.0
.NET Framework: 4.7.1 

```cs
public Task Handle(TestMessage message)
        {
            throw new Exception("whatever"); //Second level retry tests
        }

public Task Handle(IFailed<TestMessage> message)
        {
            var deferCount = Convert.ToInt32(context.Headers.GetValueOrDefault(Headers.DeferCount));
            if (deferCount >= 5)
            {
                return bus.Advanced.TransportMessage.Deadletter($"Failed after {deferCount} attempts\n\n{message.ErrorDescription}");
            }

var defer = 3 * (deferCount + 1);
            Console.WriteLine($"DEFER: {deferCount}, MINUTES: {defer}");
            return bus.Advanced.TransportMessage.Defer(TimeSpan.FromMinutes(defer));
        } 
```

Our workaround is use the `CorrelationSequence` header which is working as expected.

**Comment by mookid8000** [comment]
Found out that this was a bug 😳 when using SQS's native ability to delay message delivery, it's important that Rebus REMOVES the `rbs2-deferred-recipient` header when sending the message – otherwise, the message would be sent to the wrong queue when dead-lettering it.

This is fixed in Rebus.AmazonSQS 6.3.1, which is on NuGet.org now.

Thanks for reporting this issue! 🙂

**Comment by djhvscf** [comment]
Hi @mookid8000 after testing your fix, it is still happening. One thing to add is that we're using this library https://github.com/raol/amazon-sqs-net-extended-client-lib
